### ISSUE TITLE
English rule "a vs. an" with \ell

### ISSUE THREAD

**Issue by yzhang-gh** [valentjn/vscode-ltex#131]
**Describe the bug**
This screenshot pretty much says it.

![image](https://user-images.githubusercontent.com/7588612/94536529-4b23d200-0275-11eb-8ce4-537e5c709790.png)

**Steps to reproduce**

Create a `tex` file like this

```tex
an \(\ell \times 4\) matrix
an \(L \times 4\) matrix
```

**Comment by valentjn** [comment]
Thanks for the report. This is in between a bug report and a feature request. LT<sub>E</sub>X cannot detect all possible cases due to the first item on the [list of limitations](https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#known-issues-and-limitations), so you will always be able to find a counterexample where you get the false positive. However, detecting a command like `\ell` is still feasible.

**Comment by yzhang-gh** [comment]
Many thanks!

**Comment by valentjn** [comment]
Fix released in 7.3.0.
