### ISSUE TITLE
Improve documentation of settings with syntax examples

### ISSUE THREAD

**Issue by tretum** [valentjn/vscode-ltex#16]
**Is your feature request related to a problem? Please describe.**
I would like to have some examples for settings requiring manual altering of the settings.json.

**Describe the solution you'd like**
Especially the syntax for dummy rules, but also required escaping should be added to the README/documentation. In general an example for each setting could be useful next to the existing textual description.

**Comment by valentjn** [comment]
@tretum There are already examples for the dummy rules in the README.md, `\cite{}` and `\cite[]{}`. These are also listed in the config contributions in package.json, which should lead to VS Code's IntelliSense automatically suggest those when newly inserting the setting into your settings.json (which is why they are in the README.md, but not in the settings description in package.json). Maybe you want more complicated examples?

Some of the other settings could use some more examples though, I agree.

The escaping thing is a good point; it doesn't hurt to add that to the docs.

**Comment by valentjn** [comment]
Fixed. @tretum Thanks for the suggestion.

**Comment by tretum** [comment]
Thank you :)
