### ISSUE TITLE
Show more context (e.g., for possible spelling mistake)

### ISSUE THREAD

**Issue by yzhang-gh** [valentjn/vscode-ltex#161]
Thanks for your great work!

**Is your feature request related to a problem? Please describe.**

I usually use the Problems panel to review all the warnings

![image](https://user-images.githubusercontent.com/7588612/98088042-eedb5000-1ebb-11eb-819a-b1b304424aa4.png)

However, I need to click on every entry to check if I really need to change it. (For example, author names are reported as spelling mistakes.)

It would be better to also show the word with the warning message. (See the line above the annotation, it is a message from Spell Right extension.)

I guess there are other types of diagnostic that will benefit from this.

**Comment by valentjn** [comment]
This issue would be better directed at [microsoft/vscode](https://github.com/microsoft/vscode) (i.e., how VS Code displays problems) or [microsoft/language-server-protocol](https://github.com/microsoft/language-server-protocol). There's only one type of message for diagnostics, regardless of whether you hover over the problem in the editor, or look at it in the Problems tab. LT<sub>E</sub>X won't include context for most diagnostic types because then there would be a lot of redundant info when hovering in the editor (as in this case, you have the context directly near your mouse cursor). Plus, the context can be longer for a grammar checker like LT/LT<sub>E</sub>X (where a whole subordinate clause might be underlined) than for simple spell checkers (the same holds for the messages themselves), and the Problems tab will crop too long entries.

I implemented this for "unknown word" LT rule types (thanks for the suggestion), but I'm not convinced this would be a good thing to do for other rule types.

**Comment by yzhang-gh** [comment]
Many thanks 👍

**Comment by valentjn** [comment]
Fix released in 8.1.0.
