### ISSUE TITLE
Mac shows popup prompting to install Java

### ISSUE THREAD

**Issue by AlexanderZeilmann** [valentjn/vscode-ltex#162]
This is not really a bug report as vscode-ltex works just fine.

From time to time when I open a new vscode window, LTeX updates Java
![Bildschirmfoto 2020-11-05 um 17 15 13](https://user-images.githubusercontent.com/901391/98270616-56160480-1f8f-11eb-86e7-0602092444a0.png)

When this happens the following prompt appears as well:
![Bildschirmfoto 2020-11-05 um 17 15 20](https://user-images.githubusercontent.com/901391/98270634-5a422200-1f8f-11eb-9726-6b50b4f159a6.png)

Clicking "OK" closes the prompt and vscode-ltex continues to work just fine.
Clicking "Weitere Infos ..." ("Further information ...") open the following page in my browser https://plugins.apple.com/java-de?intent=WebStart&os_version=10.15.4&jrs_version=15.0.1 which redirects me to https://get.adobe.com/de/flashplayer/.

I am not supposed to install the Adobe Flash Player for vscode-ltex, right? Why is this prompt appearing? Is my vscode-ltex installation broken?
I am especially confused that at first, it says Java, but then the Flash Player website opens...

**Comment by valentjn** [comment]
This message is not from LT<sub>E</sub>X, it's from macOS. LT<sub>E</sub>X first tries running `java` in case a system-wide Java is installed, and only if that fails, it downloads Java itself.

My guess (I don't have a Mac) is that macOS has a "feature" of showing this popup when running `java` if it's not installed, instead of just failing with a silent error (that LT<sub>E</sub>X can catch) like every other OS.

We could make LT<sub>E</sub>X always download Java (of course only on macOS) even if there's already a system-wide one installed. That's still better than having this pretty irritating and confusing popup for the users that don't have Java.

As for the popup itself and the wrong redirect to Flash, you should report this to Apple instead.

**Comment by AlexanderZeilmann** [comment]
I guess you are right.
Running ```java``` in the terminal brings up the same prompt, but it leads to the correct website. I downloaded Java and hope that the prompt is gone.

I would vote against making macOS always download Java, but rather put a short explanation in the documentation.

Maybe the wrong redirect gets fixed once Flash is gone later this year.

**Comment by valentjn** [comment]
IMO leaving this as it is would be bad UX for LT<sub>E</sub>X for three reasons:

- It's annoying as the popup will show again after every update of LT<sub>E</sub>X, if you don't install Java system-wide.
- It's confusing as due to the missing window title and the temporal coincidence to LT<sub>E</sub>X downloading Java, users will think this message comes from LT<sub>E</sub>X.
- It's dangerous as the wrong redirect might lead users into installing software that is known for its security issues and that is very near its EOL with no security updates.

Therefore, the new default on Mac is not to use a system-wide Java installation. There will be a new setting called `ltex.java.forceTrySystemWide` which you can set to `true` to restore the original behavior.

Please [submit a bug report to Apple](https://www.apple.com/feedback/macos.html) for the wrong redirect.

**Comment by AlexanderZeilmann** [comment]
I agree with your points. Thank you for the fix. And thank you for the `ltex.java.forceTrySystemWide` setting.

I submitted a bug report to Apple, let's see how they react.

**Comment by valentjn** [comment]
(If they react at all :wink:)

Fix released in 8.1.0.
