### ISSUE TITLE
Add support to ignore whole tex files

### ISSUE THREAD

**Issue by criemen** [valentjn/vscode-ltex#19]
**Is your feature request related to a problem? Please describe.**
My preamble lives in a separate tex file.
It only contains configuration, but is still spell-checked and generates some warnings.
It would be great to have a config option which takes a list of files which are not spell-checked by LT.

**Comment by valentjn** [comment]
@Cornelius-Riemenschneider Many preamble files also contain text that should be spellchecked. Imagine a rather embarrassing typo in the title of your document! This is often set in the preamble via `\title{}`.

But I can imagine there are files where there is absolutely no text at all in them (e.g., definition of mathematical macros, Ti*k*Z figures without any text in them, etc.). So this feature request is not completely infeasible.

However, the canonical way would be using the `ltex.commands.ignore` and `ltex.environments.ignore` options to get rid of most, if not all of the warnings. Other workarounds would be using `files.exclude` (that also hides it from the Explorer, unfortunately), or just closing the file.

**Comment by criemen** [comment]
That is a good argument indeed!
I didn't know/notice closing the file is enough, so that's a good-enough workaround for me.
If you want, feel free to go ahead and close the feature request, or treat it with very low priority.

**Comment by valentjn** [comment]
@Cornelius-Riemenschneider Glad this already helped you.

Regarding the feature request (thanks by the way for the input): I'm a bit reluctant to just implement it as I'm not sure if managing diagnostics ("Problems" in the UI) should be the job of extensions, or rather of VS Code itself. I think there were/are some PRs for VS Code to add functionality such as hiding specific types (e.g., show only errors), or even ignoring/deleting diagnostics for some files.

So I'm closing this for now. But depending on demand and (the lack of) future changes in VS Code with respect to management of diagnostics, this may be reopened.

**Comment by valentjn** [comment]
VS Code 1.41 now has the ability to restrict display of diagnostics, e.g., only the active file: https://code.visualstudio.com/updates/v1_41#_problems-panel

**Comment by marcelgerber** [comment]
Hi.
I get your above arguments but would still like this option.
For example in my case the thesis contents are all in `*.tex` files, and I'm using some Markdown files alongside it to manage my todos and other stuff. These should not be spell-checked since they're just throw-away thoughts anyway.

Additionally, I'm using an university-provided template and therefore it would be nice to exclude all the spell check errors caused by that, since I can't really do much about that. I realize that I could also white-list these using `ltex.commands.ignore`, but that is more cumbersome.

**Comment by valentjn** [comment]
@MarcelGerber There's now the feature of [magic comments](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#magic-comments), which can be used to disable LT<sub>E</sub>X in individual files.

Regarding L<sup>A</sup>T<sub>E</sub>X preambles, LT<sub>E</sub>X already ignores many of the common preamble commands. If there still are false positives, and the problematic commands are not that exotic, it would be best if we added them to that list (e.g., via pull or feature request) so that other people can profit from that. (Not everybody has their preambles in separate files.)

**Comment by marcelgerber** [comment]
Hey @valentjn, thank you very much for your response.
I didn't know about these magic comments and they're indeed working well for my use case.

I would still find it great if there was an option to at least disable LT<sub>E</sub>X for all Markdown files (which could, of course, also be done with a file filter).



> If there still are false positives, and the problematic commands are not that exotic, it would be best if we added them to that list

Don't know how exotic these are, but in my case it's blocks like `\begin{textblock*}{120mm}(80mm,250mm)`, where the two numbers in parens are marked as a typo.
Other than that I also have these ignored:
```json
{
  "ltex.commands.ignore": [
    "\\DeclareAcronym{}{}",
    "\\acsetup{}",
    "\\addcontentsline{}{}{}"
  ],
  "ltex.commands.dummy": [
    "\\ac{}",
    "\\acf{}",
    "\\acs{}",
    "\\acl{}",
    "\\acfp{}",
    "\\acsp{}",
    "\\aclp{}"
  ]
}
```

**Comment by valentjn** [comment]
@MarcelGerber With LT<sub>E</sub>X 7.1.0, it's now possible to disable LT<sub>E</sub>X for some file types via the [`ltex.enabled`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenabled) setting.

Usually, `textblock`s should be checked, as there might be text with spelling errors in them (or it might just be graphics). Their parenthesis arguments are now ignored by LT<sub>E</sub>X. With "exotic" I meant obscure constructs nobody else is using and/or requiring a full L<sup>A</sup>T<sub>E</sub>X compiler to parse them. `textblock`s are not exotic ;)

`\addcontentsline` and the commands from the `acro` package are now properly handled as well. For other commands or similar feature requests, please open a new issue.

**Comment by marcelgerber** [comment]
Woah, great work there. Thank you so much!
I bought you some coffee on ko-fi for your efforts, greatly appreciated and keep up the good work!

Schöne Grüße aus Würzburg :)
