### ISSUE TITLE
Add support for user-defined pairs of commands to skip spelling error checking

### ISSUE THREAD

**Issue by jiaqi61** [valentjn/vscode-ltex#204]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
I often use the following macro when typing multiline equations, which allows me to just type `\be` rather than longer words.
`\def\be{\begin{equation}\begin{aligned}}`
`\def\en{\end{equation}\end{aligned}}`
I know LTeX can skip checking errors for contents betwen `\begin{equation}` and `\end{equation}`. However, LTeX will check the spelling errors between `\be` and `\en`, which is not I want. 

**Describe the solution you'd like**
Add support for user-defined pairs of commands such that LTeX does not check spelling errors for the contents surrounded by them.

**Describe alternatives you've considered**
I don't know an alternative.

**Additional context**
None

**Comment by valentjn** [comment]
I'm not convinced this would be a good feature as this would make it even more complicated (together with [ignored commands](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexcommands) and [environments](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexenvironments), [magic comments](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#magic-comments), [babel commands](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#multilingual-latex-documents-with-the-babel-package), etc.) for users to see in which parts of the code LT<sub>E</sub>X is active with which settings.

Using macros that switch things is pretty plain-T<sub>E</sub>X-ish, it's a bit like `\bf` vs. `\textbf`. L<sup>A</sup>T<sub>E</sub>X introduced `\begin` and `\end` for a reason and all sorts of macros that accept arguments, to switch things only for the contents of the environment/for the arguments. As a L<sup>A</sup>T<sub>E</sub>X tool, LT<sub>E</sub>X will rather stick to L<sup>A</sup>T<sub>E</sub>X conventions than support everything that's possible with T<sub>E</sub>X.

I suggest one of the following workarounds (not tested):

- `\newcommand{\be}[1]{\begin{equation}\begin{aligned}#1\end{aligned}\end{equation}}`, add `"\\be{}": "ignore"` to [`ltex.latex.commands`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexcommands); this is even less keystrokes than your approach
- `\newenvironment{be}{\begin{equation}\begin{aligned}}{\end{aligned}\end{equation}}`, add `"be": "ignore"` to [`ltex.latex.environments`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexenvironments); if that's too many keystrokes for you, you could define some kind of editor shortcut to insert a template

Notes:
- This assumes you meant `\def\en{\end{aligned}\end{equation}}` instead of `\def\en{\end{equation}\end{aligned}}`.
- I don't recommend the above workarounds. LT<sub>E</sub>X doesn't just ignore inline and displayed equations. If you switch to text mode inside them, the text will still be checked, e.g., `\text` or `\intertext`. For instance, this will check proper punctuation of your equations. This functionality will be lost if you use custom macros or the workarounds above.

**Comment by jiaqi61** [comment]
Thanks. I'll try the solutions you proposed.
