### ISSUE TITLE
How do I spell-check multiple languages?

### ISSUE THREAD

**Issue by yuanhao-chen-nyoeghau** [valentjn/vscode-ltex#21]
**Describe the solution you'd like**
Being able to assign a list of languages to ltex.language, e.g., "ltex.language": ["en-GB", "zh-CN"]

**Comment by valentjn** [comment]
@edward-martyr What do you mean with "multiple languages?" Do you have multiple languages in one workspace, but all the files are single-language each? Or do you have multiple languages in one file?

In the former case, you can use [VS Code's multi-root workspace feature](https://code.visualstudio.com/docs/editor/multi-root-workspaces) to have different settings (which include `ltex.language`) for different resources. However, LanguageTool seems to have some kind of language detection, so maybe this could be simplified (if the L<sup>A</sup>T<sub>E</sub>X artifacts don't confuse the detector).

In the latter case, you're out of luck, [LT doesn't have multilingual support right now.](https://github.com/languagetool-org/languagetool/issues/766)

**Comment by yuanhao-chen-nyoeghau** [comment]
@valentjn Thanks for the comment. In most cases, I work with multiple languages, each in a separate project, so that helps a lot. However, there are occasions where I work with Chinese and Japanese, or English and Chinese in a single file. I guess I'll have to wait until any relevant updates.

**Comment by yuanhao-chen-nyoeghau** [comment]
Especially considering that Chinese and Japanese share the same script, it would be hard to differentiate and spell-check them simultaneously. It would be much easier in the case of English and Chinese.

**Comment by valentjn** [comment]
So LT has the concept of "alternative languages," which means that if a word is unknown in the main language, then the word will be looked up in these alternative languages. If it's in one of those, then there won't be a spelling error.

However, I'm a bit reluctant to implement this. This would only be about spell checking, not grammar checking. And the current architecture of LT<sub>E</sub>X is focused on single languages - each language has its own user dictionary and optionally additional rules from neural networks or Word2Vec. I could also imagine the consumption of resources (CPU, memory) would increase even further for keeping these languages in memory. So this would be a big change, and then you don't even have grammar checking.

I'll mark this issue as `upstream` as I would wait until LT has proper multi-lingual support. In the meantime, if someone wants to implement these alternative languages, I won't stop them :wink:

**Comment by ghost** [comment]
We could :
1. Specified several languages
2. Tests a file against all of those
3. Choose the answer with the fewer errors as matched language

**Comment by valentjn** [comment]
@St-Ex-savadenn I think the current scope of the issue is having multiple languages in a single file. If your files are in one language each, and in different folders, then you can use multiple `config.json`s with different values for `ltex.language`.

A possibility to cope with multiple languages in one file could be magic comments. Something like `% ltex: language=en-US` in L<sup>A</sup>T<sub>E</sub>X would work, if your language parts are not just single words. You could also use that for whole files, if the comment is at the top.

Just for the record, LanguageTool has a built-in language detection via https://github.com/optimaize/language-detector. It's based on *n*-grams, so it's very fast. Downside is that it only gives you generic languages like `en` or `de`, instead of specific variants like `en-US` or `de-DE`, which won't give you spelling errors, only grammar errors.

**Comment by nweldev** [comment]
@valentjn What do you mean by `config.json`? For now I only know about the VSCode `settings.json`. Therefore, I can't define different languages for different folders in the same workspace. If there is a specific configuration file for Ltex, it's awesome :smiley: But I wasn't abble to find any mention of it in the docs.

**Comment by valentjn** [comment]
@noelmace Sorry, I meant `settings.json`, not `config.json`. There's no extra configuration for LT<sub>E</sub>X, apart from what can be set in `settings.json`. I was talking about multi-root workspaces. [It's possible to have multiple workspaces in one project, each with its own `setting.json` (even nested).](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings) It's probably overkill to use this just for having different languages. Therefore, I did a first implementation of those magic comments, since that's more flexible. It will be in the next release.

**Comment by valentjn** [comment]
The code for magic comments is now in `master`. It will be in the upcoming 5.0.0 release. Here's a sneak preview for the syntax: https://valentjn.github.io/vscode-ltex/docs/advanced-features.html#magic-comments. I think this should be enough for most multilingual users.

**Comment by valentjn** [comment]
Fix released in 5.0.0.

**Comment by RenatoLopes771** [comment]
For those coming from google, if you put ```ltex.language": "auto"``` it can actually work with multiple languages. This is not the best way to go about things as it's advised against using this setting in the documentation. I'm using with portuguese brazilian and english and it's working well so far. 

If I have a single sentence in english it doesn't give me errors, but if I have a english word on a portuguese brazilian sentence it gives me the "estrangeirismo" error, which is when you use a word outside the language to describe something. Granted it's not perfect, some english phrases have the "estrangeirismo" error still but it's not everything if you set the language to just pt-BR.

TIP: You can create a .vscode folder and a settings.json file inside that folder to keep this setting only to that project, while having a main language in your standard settings.json for your other projects.

![image](https://github.com/valentjn/vscode-ltex/assets/52989307/8d4d5947-f5ce-48d1-bbe0-d2551fce1155)
