### ISSUE TITLE
Do not check content enclosed by dollar signs in markdown

### ISSUE THREAD

**Issue by we-taper** [valentjn/vscode-ltex#210]
**Is your feature request related to a problem? Please describe.**

Currently, in many favors of markdown (e.g. [pandoc][1], [jupyter][2], [mathoverflow][3]), contents surrounded by single or double dollar signs are treated as latex math commands. But currently ltex treats them as normal text and checks them for grammar errors (including marking `$$` as a grammar error).

[1]: https://pandoc.org/MANUAL.html
[2]: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html#LaTeX-equations
[3]: https://mathoverflow.net/editing-help#latex

Example:

```markdown
# Content

$$
\langle 1 \rangle
$$
```

Here, `$$`, `rangle`, and `langle` are marked as possible spelling mistake, when in fact they are latex commands.

**Describe the solution you'd like**

Either ignore checking the grammar for the content matching:

- single dollar sign: regex `\$([^\$]+)\$`
- double dollar sign: regex `\$\$([^\$]+)\$\$`

Or treat them as tex math environments.

**Describe alternatives you've considered**

At the moment, adding the following lines in the `ltex.hiddenFalsePositives.en-US.txt` reduces the amount of spelling mistakes reported by ltex:

```
{"rule":"MORFOLOGIK_RULE_EN_US","sentence":"\\$\\$([^\\$]+)\\$\\$"}
{"rule":"MORFOLOGIK_RULE_EN_US","sentence":"\\$([^\\$]+)\\$"}
```

**Additional context**

None

**Comment by valentjn** [comment]
Thanks for the feature request. I'm not sure the regexes you provide are suitable. What about `The pen costs $2, but the apple costs $1.`? Plus, can I have a literal dollar sign (maybe escaped somehow) in a math context?

How do the parsers you mention actually handle this?

**Comment by we-taper** [comment]
Thanks for the reply. That is a very interesting question that I haven't thought about. I did a bit of research and the situation is a bit messy.

In pandoc, it is [described that](https://pandoc.org/MANUAL.html#extension-tex_math_dollars):

> Anything between two $ characters will be treated as TeX math. The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, $20,000 and $30,000 won’t parse as math. If for some reason you need to enclose text in literal $ characters, backslash-escape them and they won’t be treated as math delimiters.
>
> For display math, use $$ delimiters. (In this case, the delimiters may be separated from the formula by whitespace.

For both jupyter notebook, and MathOverflow, they incorrectly parsed your example into mathematical equations.
However, jupyter notebook supports exporting to formats other than HTML, which [uses pandoc for conversion](https://nbconvert.readthedocs.io/en/latest/install.html#installing-pandoc). So I guess following pandoc's standard would be most useful?

**Comment by valentjn** [comment]
I discovered that LT<sub>E</sub>X's Markdown parser Flexmark supports a [long list of extensions](https://github.com/vsch/flexmark-java/wiki/Extensions). [One of them](https://github.com/vsch/flexmark-java/wiki/Extensions#gitlab-flavoured-markdown) adds support for math. The caveat is that the syntax is that of [GitLab Flavored Markdown](https://gitlab.com/gitlab-org/gitlab/blob/master/doc/user/markdown.md#math), so ``$`E = mc^2`$`` for inline math and
````markdown
```math
a^2 + b^2 = c^2
```
````
for display math. Would that still be acceptable for you? I enabled the extension in LT<sub>E</sub>X, so this would already be supported in the next release, while writing a custom parser/extension would take more time.

**Comment by we-taper** [comment]
Thanks for that update. Unfortunately, I have almost all equations in double dollar (non-inline) math environments and the fenced math code block isn't supported by my markdown previewer ([Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)) and post-processor (pandoc). 

But I agree there is a dependency on the upstream and I might (if I have time) raise issues there in Flexmark for an extension.
At the moment I can fiddle with the `ltex.hiddenFalsePositives` settings for a temporary solution.

**Comment by valentjn** [comment]
FWIW, it's also possible to [temporarily disable LT<sub>E</sub>X with magic comments](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#magic-comments). Of course, putting magic comments everywhere is not a satisfying solution.

I got annoyed by the lack of this feature myself today. I'll check how hard this is to implement. This depends on when we can parse stuff, before or after Flexmark splits the code into paragraphs/an AST. "After" would probably be worse, because the closing `$$` can be in a different paragraph than the opening `$$`.

**Comment by valentjn** [comment]
Turns out Flexmark can do both by [allowing extensions to be block parsers or inline parsers](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions/00bed2824bbc16ad05266d2a55c23913fa719b1f), amongst others.

A rudimentary version of this feature is now implemented. It's not nearly as powerful as LT<sub>E</sub>X's processing of L<sup>A</sup>T<sub>E</sub>X files (regarding punctuation, dummy words with vowels, etc.), but it should be a good start.

**Comment by valentjn** [comment]
Feature released in 8.4.0.

**Comment by we-taper** [comment]
Thanks. I just tested it and it works as expected! :+1:

**Comment by universemaster** [comment]
> Turns out Flexmark can do both by [allowing extensions to be block parsers or inline parsers](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions/00bed2824bbc16ad05266d2a55c23913fa719b1f), amongst others.
> 
> A rudimentary version of this feature is now implemented. It's not nearly as powerful as LTEX's processing of LATEX files (regarding punctuation, dummy words with vowels, etc.), but it should be a good start.

Do you have a road map to add these additional features? I am currently getting a lot of

- "Unpaired symbol: )" and
- "If/So at the beginning of a sentence usually requires a 2nd clause."

type errors because I have dollars in between.  Should I open a new issue?

**Comment by valentjn** [comment]
@universemaster You shouldn't be getting these errors, if I understand it correctly. What I meant with &ldquo;punctuation&rdquo; is that currently, LT<sub>E</sub>X won't recognize if a displayed formula ends with a full stop (i.e., the period is inside the displayed formula) as it does in L<sup>A</sup>T<sub>E</sub>X mode. What I meant with &ldquo;dummy words with vowels&rdquo; is that currently, LT<sub>E</sub>X won't recognize that a formula starts with a vowel when spoken (e.g., `an $n$-dimensional space` will give a false positive, because LT<sub>E</sub>X doesn't see the formula is spoken as &ldquo;enn,&rdquo; which starts with a vowel), which it does in L<sup>A</sup>T<sub>E</sub>X mode. I wouldn't expect neither of your error messages for these things. So please open a new issue if you think this is due to wrong parsing of dollar signs.

**Comment by mateosss** [comment]
While math enclosed by `$$` is effectively not being handled. Inline math enclosed by `$` is still reporting spelling mistakes. Is this expected?

EDIT: It seems to get fixed when using `<!-- LTeX: language=en-US -->` but I'm writing a document with language `es-AR`. Any recommendations? The reported error is `MORFOLOGIK_RULE_ES`.
