### ISSUE TITLE
Pattern matching for `ltex.latex.commands` and `ltex.latex.environments`

### ISSUE THREAD

**Issue by flindeberg** [valentjn/vscode-ltex#226]
**Is your feature request related to a problem? Please describe.**
I have a large amount of user defined commands / macros which I would like to properly use with ltex without having to enter them manually. There are two reasons for not entering them all manually:

1. I have quite a lot of them
2. They change constantly, i.e. more are added and removed.

**Describe the solution you'd like**
Being able to write this is settings would solve my problems, since the commands in my example all share a common format:
```
 "ltex.latex.commands": {
        "\\my.*fullpl{}": "pluralDummy",
        "\\my.*full{}": "Dummy",
        "\\my.*acn{}": "Dummy",
        "\\my.*draw[][]{}[]":"Ignore",
        // and so forth
```
Or any other form of pattern matching, it does not have to be regex.

This would also help fix things with `\gls`-commands, since now you have to add all of them manually (i.e. \Gls, \gls, \Glspl, \gls, and so forth).

**Describe alternatives you've considered**
I have considered just generating a this list based on my latex files, and I did it once, but maintaining it is quite a hassle. 

I tried different forms of pattern matching to see if any of them worked, but it does not seem like it =(

**Comment by valentjn** [comment]
The problem is that this would result in a significant cost in performance. You might not know, but [as the documentation says](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexcommands), there's already a [rather long list of commands that are handled by default](https://github.com/valentjn/ltex-ls/blob/46333a38c8b246478859e6e989f345baba2761e0/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/LatexAnnotatedTextBuilderDefaults.java) by LT<sub>E</sub>X.

The current implementation takes this list, merges it with the user-defined list, and creates a hashmap by grouping command signatures with the same name together. Now, when a document is parsed and the parser encounters something that looks like a command, the command signatures with matching name are retrieved from the hashmap (constant time). LT<sub>E</sub>X then only has to check these few command signatures (if the number and type of brackets matches) instead all of them.

If we used any kind of pattern matching, we'd probably have to check all command signatures for all commands of the whole document on every keystroke (at least, we wouldn't be able to use the hashmap lookup anymore). Plus, each check would be much more expensive than a simple check for string equality.

If you have common commands (like those of glossaries) that you think others might be using as well, it's best to just request them to be added to the list with the defaults. I added a few of them (of course, glossaries has a lot more; I added those that were used in the Beginner's Guide of glossaries), so thanks for the suggestion.

If you have a lot of custom commands with similar names, you could refactor the changing part of the names into an extra argument, which can be used to select the right variant inside the common command, e.g., `\myXYZacn{...}` → `\myacn{XYZ}{...}`. Then you'd only have to add `\myacn` to the list. So I think the cost-benefit value of this feature would be probably somewhat limited.
