### ISSUE TITLE
Exclude LaTeX commands in Markdown files

### ISSUE THREAD

**Issue by hippwn** [valentjn/vscode-ltex#227]
**Is your feature request related to a problem? Please describe.**
As a Pandoc user, I often rely on LaTeX commands inside my Markdown files and LTeX flags them as errors. 

**Describe the solution you'd like**
I've two solutions in mind:
1. Consider LaTeX as not analyzed in Markdown;
2. Add support for custom pattern recognition in Markdown files to exclude them.
Actually, I'd like both since there are other patterns (added by Pandoc or some filters I use) that will not be recognized as LaTeX. 

**Describe alternatives you've considered**
I had a look at the Markdown nodes provided by `flexmark-java` but I haven't found an easy way to add new nodes.

**Additional context**
I understand that I ask two different things in this issue, and I'm sorry for that. I'm also sorry if it is already feasible, I didn't manage to find it in the documentation.

**Comment by valentjn** [comment]
Can you give an example? How do you use L<sup>A</sup>T<sub>E</sub>X commands in Markdown outside of inline/display math (`$...$` and `$$...$$`)? For math, there's already #210.

**Comment by hippwn** [comment]
I use literal LaTeX commands like you would in a LaTeX document. Those can be their own paragraph or used inside one:
```markdown
This is a random text which use a lot of *acronyms* like \gls{iot}.

\newpage
```
In this example, `\gls{iot}` will be highlighted as error, just like `\newpage`.
I need this because I then use Pandoc and a LaTeX template of mine to build PDFs. Raw LaTeX is often used when Markdown's features are not enough. Thank you for your help.

**Comment by valentjn** [comment]
I see. IMO that's L<sup>A</sup>T<sub>E</sub>X with some Markdown in it instead of the other way around. In fact, I get less spelling errors (zero in the next release, which handles `\gls` correctly by default) when setting the language mode to `latex` than when setting it to `markdown`.

Simply ignoring L<sup>A</sup>T<sub>E</sub>X commands at all is not really an option. You will still get an error for your example (`Don't put a space before the full stop.`). Besides, not every word that starts with `\` might be a L<sup>A</sup>T<sub>E</sub>X command. So you need a correct parser.

L<sup>A</sup>T<sub>E</sub>X like this inside Markdown is a [proprietary extension of Pandoc's Markdown](https://pandoc.org/MANUAL.html#extension-raw_tex), which means we would probably have to use Pandoc as parser. It would be a very big change, but it would be possible to reopen #91 to add support for this, as jgm/pandoc#4565 implemented the necessary source code mapping. The problem is that [the `raw_tex` extension is only supported for the `markdown` reader and a few others](https://pandoc.org/MANUAL.html#raw-htmltex), but source code mapping is only supported by the `commonmark`, `commonmark_x`, or `gfm` readers, which don't support `raw_tex`. Without source code mapping, we don't know where to display spelling errors. So I think this is an upstream issue in Pandoc. Even if it's fixed, I'm not sure if we can handle the rather long parsing times of Pandoc (it would have to be executed on every keystroke).

Of course, it might also be possible to somehow combine the existing Markdown and L<sup>A</sup>T<sub>E</sub>X parsers of LT<sub>E</sub>X. But this is absolutely not easy, as such a format is really neither Markdown nor L<sup>A</sup>T<sub>E</sub>X, but the parser would have to tell those two apart.

I'd suggest to either
- fully switch to L<sup>A</sup>T<sub>E</sub>X (IMO the benefit of having Markdown is not really large at that point, you just save a few keystrokes), or
- switch the language mode to `latex` and hope that there are less errors, or
- [use `ltex.hiddenFalsePositives` and regular expressions to get around some of the errors](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#hiding-false-positives-with-regular-expressions) (the first caveat listed there only applies to L<sup>A</sup>T<sub>E</sub>X commands inside actual L<sup>A</sup>T<sub>E</sub>X documents).

**Comment by hippwn** [comment]
Hi. I'm sorry for not responding sooner, I've been quite busy. Thank you for the complete response though.

I get your point, this feature is probably very niche and not easy to implement. However, it's clearly not LaTeX with a bit of Markdown (I feel like my example may have been misleading), I'm talking of huge Markdown documents that happen to have some LaTeX commands inside raising errors. The only option that would be worth considering IMO is the use of regular expressions to exclude the commands that cause problems, but I haven't managed to do that with `ltex.hiddenFalsePositives`. Would you mind giving me a hint (or an example with `\gls{}` at least)?

**Comment by valentjn** [comment]
Regarding the example, this is the reason the issue template suggests to give actual (i.e., representative) examples for feature requests. Otherwise, it's difficult for me to get an idea of how the proposed feature should look like (what should be supported, what not, etc.).

Regarding hiding false positives, this depends on what L<sup>A</sup>T<sub>E</sub>X commands you actually use and how you use them. In your example, you can just add `newpage`, `gls`, and the key of the acronym to the user dictionary, and you'll end up with zero diagnostics. `ltex.hiddenFalsePositives` is only for more difficult cases. But I won't promise you can get rid of all diagnostics.

FWIW, Pandoc can translate Markdown+L<sup>A</sup>T<sub>E</sub>X to pure L<sup>A</sup>T<sub>E</sub>X code to ease transitioning (`pandoc -f markdown -t latex -i input.md`).

**Comment by hippwn** [comment]
I totally get your point, that's fair. My example was badly chosen and I should have explained my use case more clearly.

I didn't know I could simply add the commands in the dictionary as is, I'll try that and hope it works. 

Thanks!!
