### ISSUE TITLE
List of suggestions to replace all occurrences

### ISSUE THREAD

**Issue by libinvarghese** [valentjn/vscode-ltex#23]
I usually have multiple instances of the same error. Instead of individually fixing them, it would be great to have an option to replace all occurrence with a fix.

For instance some the errors I usually encounter are:
1. Consider using an m-dash if you do not want to join two words.
1. Please add a punctuation mark at the end of paragraph.
1. This sentence does not start with an uppercase letter
1. In British English, for some verbs, both ~s and ~z spellings are possible. By default, the rule for Oxford spelling is on for verbs.

**Comment by valentjn** [comment]
@libinvarghese Great suggestion. This is implemented in the upcoming release of LT<sub>E</sub>X. To trigger, select a range of text, which contains the LanguageTool diagnostics, and execute *Command Palette* (usually `Ctrl+P`) → *Quick Fix...*, i.e., don't hover with your mouse over the text (you would only be able to fix individual diagnostics this way). You can also use the direct shortcut `Ctrl+.` instead of `Ctrl+P` → *Quick Fix...*.

**Comment by valentjn** [comment]
Fixed in 4.7.8.
