### ISSUE TITLE
Can not reset customer settings for latex command

### ISSUE THREAD

**Issue by Jieli12** [valentjn/vscode-ltex#232]
It seems that I still can't reset the customer setting for latex command. I disabled all extensions except latex workshop and ltex.  For example, I want to ignore this latex command **\lstset{style=mylststyle}**. In the settings.json file, I add
`"ltex.latex.commands": {
    "\\\\lstset{}": "ignore"
  }`
But It doesn't work, would you please help me to solve this problem?

_Originally posted by @Jieli12 in https://github.com/valentjn/ltex-ls/issues/27#issuecomment-765045015_

**Comment by valentjn** [comment]
Ahh, I didn't know that VS Code does that. I always edit my settings directly in the `settings.json`. This is a very valuable hint, thank you.

This is a bug (error) in the documentation of vscode-ltex, which is why I moved the issue there. I fixed this, the description of the setting should be clarified in the next release. Thanks again!

**Comment by valentjn** [comment]
Documentation fixed in 8.3.0.
