### ISSUE TITLE
Hide or shorten error codes in problems list

### ISSUE THREAD

**Issue by bwegge** [valentjn/vscode-ltex#233]
With most "Diagnostic Severity" levels, LTeX lists the identified spelling issues in the "Problems" tab in VS Code, where each issue consists of an explanation text plus some identifier string consisting of "LTeX - " and some all-caps code.

As these appended identifier strings are often rather long and all-caps, they take up a significant amount of space. What is more, when the "Problems" tab is narrow (e.g. when it's put on the side, not the bottom of the screen, see screenshot below), VS Code puts precedence on the identifier strings instead of the explanation, so while the codes are kept readable, the explanation is not. For a human user, this is quite counterintuitive since I'm really interested in the human-readable explanation and not the string "LTeX - " + code.

Is it possible to add an option to either shorten or entirely hide these identifier strings, or give precedence to the explanation instead of the identifier strings?

Thanks and best
![image](https://user-images.githubusercontent.com/7688998/105635362-a9974080-5e62-11eb-8154-f16c027457f1.png)

**Comment by valentjn** [comment]
I moved the rule ID from the source of the diagnostic (that's what the part with the `LTeX -` is called) to the end of the message of the diagnostic, so that the rule ID will be truncated instead of the actual message of the rule. I think this is the best solution for most users. An additional setting shouldn't be necessary for this.

Regarding the visual layout, this should be a feature request for VS Code itself (see [microsoft/vscode](https://github.com/microsoft/vscode)). LT<sub>E</sub>X can't control which one of source and message is truncated.

**Comment by bwegge** [comment]
That was quick, thanks for the prompt response (and also the extension, which is great).
The proposed solution sounds good for me, will gladly test the new release.

**Comment by valentjn** [comment]
Fix released in 8.4.0.

**Comment by bwegge** [comment]
Works fine for me as expected, thanks a lot!
