### ISSUE TITLE
Ignore Code Blocks in Markdown

### ISSUE THREAD

**Issue by ishehadeh** [valentjn/vscode-ltex#26]
**Is your feature request related to a problem? Please describe.**
Code blocks usually can't be grammar checked accurately, but they are not ignored by vscode-ltex.

**Describe the solution you'd like**
I'd like the option to ignore everything between back ticks, when checking markdown.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by valentjn** [comment]
@IanS5 Thanks for the suggestion! The upcoming release of LT<sub>E</sub>X will bring [quite a few changes](https://github.com/valentjn/vscode-ltex/blob/master/CHANGELOG.md#479--the-markdown-resonance) (that means hopefully improvements...) to the handling of Markdown documents. The change relevant to this issue is that there will be `ltex.markdown.ignore` and `ltex.markdown.dummy` settings that will work analogously to the existing L<sup>A</sup>T<sub>E</sub>X ignore/dummy mechanism. By default, code blocks (` ```...``` `) will be ignored, while auto-links (`<https://...>`) and inline code (`` `...` ``) will be replaced with dummy words. This can be overridden by the new settings.

**Comment by valentjn** [comment]
Fixed in 4.7.9.
