### ISSUE TITLE
Support for languagetool 4.8

### ISSUE THREAD

**Issue by gHerzmann** [valentjn/vscode-ltex#30]
**Is your feature request related to a problem? Please describe.**
On Arch Linux the languagetool package is already at version [4.8](https://github.com/languagetool-org/languagetool/tree/v4.8). The LTEX extension does not work on my system and I guess it's because of the version mismatch.

**Describe the solution you'd like**
I would like to know if there is a way to make the extension work with languagetool 4.8.

**Comment by valentjn** [comment]
@gHerzmann LT<sub>E</sub>X comes with LT included (4.7 in this case), only Java is needed. So theoretically, it should be independent of existing installations of LT. In reality, it might be that it interferes somehow. Not sure what's true in your case.

Anyway, LT<sub>E</sub>X should be updated to LT 4.8, so that's a valid point.

Edit: I would postpone it for a short period of time, since [LT 4.9 releases soon](http://wiki.languagetool.org/roadmap).

**Comment by valentjn** [comment]
This is fixed with LT<sub>E</sub>X 4.9.0, which uses LT 4.9.
