### ISSUE TITLE
Docs: how to ignore a markdown block based on its syntaxe

### ISSUE THREAD

**Issue by nweldev** [valentjn/vscode-ltex#31]
This is more a question than a bug, as there is no documentation for this use case.

**Description**
I want to ignore all [Vuepress Code Snippet Import](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets) blocks in my markdown files. `ignoreRuleInSentence` permit to do that, but based on the README it seems like a hack, and I guess there is a better approach for that, as this increased memory & CPU consumption.

**Steps to reproduce**

1. Add a Vuepress Code Snippet Import block to a markdown file

```markdown
Lorem ipsum:

<<< @/path/to/a/file.js

Lorem ipsum dolor ...
```

2.  A bunch of LTex warnings should show for this block. Click on one of these warnings, and select "ignore rule in this sentence"
3. Go to VS Code settings, and remove the end of the sentence in `ltex.ignoreRuleInSentence` in order to match all sentences starting with `<<< @/`. Here is an example :

```json
{
  "ltex.ignoreRuleInSentence": [
    {
      "rule": "FR_SPELLING_RULE",
      "sentence": "^\\Q<<< @/../\\E"
    },
    {
      "rule": "DOUBLE_PUNCTUATION",
      "sentence": "^\\Q<<< @/../\\E"
    }
  ]
}
```

4. Restart VS Code. All LTex warnings disappeared.
5. Go to Help > Open Process Explorer : (small) memory consumption increased (using `top`, we can see that CPU load increased too)

**Comment by valentjn** [comment]
@noelmace What exactly is the bug or your question?

**Comment by nweldev** [comment]
Sorry @valentjn it wasn't clear enough :sweat_smile: 

So, to rephrase that: is there a better way to ignore some markdown blocks based on their syntax?

Also:
1. Is `ignoreRuleInSentence` supposed to be used this way? (wording and performances make me think it doesn't)
2. What's the exact format for this option? Looks like kind of a regex, but not exactly :shrug: Notice I removed the `$` because it doesn't work if I don't.
3. Should we think about a better way to do that? Maybe a dedicated option?

Ultimately, this could be considered a "discussion + request for doc" issue :wink:

**Comment by valentjn** [comment]
@noelmace Thanks for the clarification.

1. Basically yes. The primary way to use `ignoreRuleInSentence` was/is by using the respective quick fix. But it's also possible to manually edit the sentence. The description wasn't really clear about this. I've clarified this now (see e66b3a3).
2. It is simply a [Java-compatible regex](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html).
Basically, LT tokenizes the document into so-called "sentences" (usually based on periods). After getting the matches from LT, LT<sub>E</sub>X checks for each of the rule matches if the sentence, in which the rule occurred, matches one of the regexes given in `ignoreRuleInSentence`. The reason for it being a regex instead of a plain string is that sometimes, especially in L<sup>A</sup>T<sub>E</sub>X documents, parts of the text such as formulas are replaced by "dummy" words which include a counter as a suffix. This is simply to avoid LT matches of repeated words. The regex can cope with this variable suffix.
I guess you have to remove the `$` because the LT sentence continues after the `<<< @`. Probably the whole line is an LT "sentence". You can see the sentence if you use the quick fix and look for the new entry in `settings.json`.
3. Hm. I think this is a pretty special case, and I haven't heard of VuePress before. As long as it works for you, we shouldn't introduce even more settings as there already are.

Regarding the performance, there was an issue affecting the performance when using ignore rule/sentence pairs (see #29). It should be much faster now.

**Comment by nweldev** [comment]
Great, Thx.
