### ISSUE TITLE
Support HTML

### ISSUE THREAD

**Issue by sanmai-NL** [valentjn/vscode-ltex#342]
**Is your feature request related to a problem? Please describe.**
HTML is a popular content writing format, e.g. for educational materials. Currently, LTEX regards HTML documents as plain text. This results in a lot of spurious writing error markings.

**Describe the solution you'd like**
Please support HTML, even if rudimentary.

**Describe alternatives you've considered**
Other extensions have their own problems

**Additional context**
None.

**Comment by valentjn** [comment]
Thanks for the suggestion. I'm currently working on XHTML support (this just means your HTML documents must be valid XML), because HTML parsing is hard. The requirement for the Java HTML parser that it must preserve source code positions while parsing [eliminates the obvious alternatives like jsoup](https://stackoverflow.com/a/13844632) (old reply, but still holds). XML parsing on the other hand is easier, plus I always had a preference for XHTML.

**Comment by valentjn** [comment]
This is implemented now. Don't expect too much from it, it's very basic.

**Comment by valentjn** [comment]
Fix released in 10.5.0.
