### ISSUE TITLE
Grammar-/spellcheck in all inline comments, not only in latex

### ISSUE THREAD

**Issue by hpvd** [valentjn/vscode-ltex#350]
**Is your feature request related to a problem? Please describe.**
Good spelling and grammar in documents written in latex and co is gorgeous.
But there is an other place where broken spelling and grammar is also somehow frustrating:
in comments within code.
This is not only true for inline-comments in latex (where comments are indicated with `%` ), but in any coding language.
Beside correct spelling and grammar in comments 
- can be seen as some kind of quality indicator,
- it ensures comprehensibility of comments, and
- there is also another not that obvious practical problem:
Having broken spelling in comments make it hard to find the place in code which one has in mind to work on, because there are no results when searching for word or phrases one think one has used in comments...

**Describe the solution you'd like**
Use the developed matured technology of this extension
also for spelling and grammar check in all comments of (m)any code language(s),
possibly in the same languages the very liked vs-code extension "better comments" supports (it makes it possible to categorize and highlight/colorize comments in an easy way) , see https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
=> the result would be "even better comments" :-)

**Describe alternatives you've considered**
keep on writing comments with spelling and grammar errors....
...and keep being faced with the 3 problems mentioned above.

**Additional context**
none

**Comment by hpvd** [comment]
Optimized issue description

**Comment by valentjn** [comment]
I'm not sure about this:

- Why only inline comments and not also block comments in other languages?
- What about the huge number of false positives this will yield for code that has been commented out? (Plus, there will a lot of false positives due to variable names/inline code snippets even in natural-language comments.)
- What about (detection of) different markup styles in documentation, like Doxygen, reStructuredText, etc.? (Without detection, this will again result in a lot of false positives.)
- How can we detect comments without writing/relying on full parsers of the languages?

**Comment by hpvd** [comment]
thanks for these thoughts!
Yes this are all valid points. Maybe I was a little to enthusiastic regarding further possibilities when using your great extension the first time :-)

just a quick shot:
Maybe one possibility would be to work close together with/rely on the mentioned "better comments"- extension, and let this one do some part of the work: only check comments which have been identified and highlighted/colored by this extension...

**Comment by hpvd** [comment]
with 1,893,354 installs the community / demand for this extension seems pretty big, which should keep it getting better in identifying the right "comments"...

**Comment by valentjn** [comment]
This is now implemented upstream, but it will be opt-in (add the language to [`ltex.enabled`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenabled)). During tests, I saw a lot of false positives in a small sample of large GitHub repositories.

Note: Only comments in programming languages (C++, Java, etc.) will be checked, not in the markup languages LT<sub>E</sub>X already supports (there should be no need to check those, either).

**Comment by hpvd** [comment]
Awesome many thanks!

Just a question: why not checking comments in markup languages like LaTeX?

e.g. when doing collaboration on writing documents/papers with colleagues, several people would see and use the comments.
Please see example:

![2021-07-20_16h07_39](https://user-images.githubusercontent.com/5681880/126338505-01e9da24-3b95-4728-9108-4e6e7b07a339.png)

**Comment by valentjn** [comment]
The main reason is that it would be pretty complex to implement it in the current framework.

However, as I said, it isn't really useful for markup languages. When you read a program, in order to understand it, you read the code and its comments, which are therefore part of the code/program, in a way. When you read a L<sup>A</sup>T<sub>E</sub>X document, you usually read the PDF and not the code. This is probably the reason vanilla Markdown doesn't support comments.

Another reason is that it wouldn't be possible to make it opt-in without an additional setting, in contrast to programs.

Finally, for todo notes, you should really be using `\todo`, because it's easy to forget to solve a todo issue if it's not clearly marked in the output with red text or similar. LT<sub>E</sub>X already has special support for `\todo`, see #42 and #63.

**Comment by valentjn** [comment]
Feature released in 11.0.0.

**Comment by GitMensch** [comment]
For anyone coming here searching about the "inline comment _after_ code" feature: it works with the command `ltex.checkSelection`.
