### ISSUE TITLE
Documentation for shortcut to command

### ISSUE THREAD

**Issue by lrnv** [valentjn/vscode-ltex#363]
I found very cumbersome to do Ctrl+; then choose 'Use ...' at every error. Browsing the repo and stuff, I found this comment: 

https://github.com/valentjn/vscode-ltex/issues/297#issuecomment-817963890

which shows how to bind a keyboard shortcut to this action. 

Is there also keyboard functions that we could bind to "Add to dictionary" and/or "False Positive" ?

Anyway, I think this should definitely be in the documentation ! Maybe in the FAQ ?

**Comment by valentjn** [comment]
Thanks for the suggestion to add this to the docs.

As for the other kinds of quick fixes: Theoretically, you should be able to supply `addToDictionary`, `hideFalsePositives`, and `disableRules` instead of `acceptSuggestions` in `keybindings.json`. However, at least for me, VS Code displays `No code actions for 'quickfix.ltex.addToDictionary' available` when pressing the keyboard shortcut at a diagnostic that has that quick fix.

I think that's a bug in VS Code. The difference between `acceptSuggestions` and the other kinds of quick fixes is that the code action corresponding to `acceptSuggestions` is [associated to a `WorkspaceEdit`](https://github.com/valentjn/ltex-ls/blob/23f83f2fd0e4fea4930bbbb0997fc5f23d7ff576/src/main/kotlin/org/bsplines/ltexls/server/CodeActionGenerator.kt#L127-L131), but the others are [associated to a `Command`](https://github.com/valentjn/ltex-ls/blob/23f83f2fd0e4fea4930bbbb0997fc5f23d7ff576/src/main/kotlin/org/bsplines/ltexls/server/CodeActionGenerator.kt#L176-L179). However, I don't see a reason why VS Code shouldn't be able to run those quick fixes, too. Please refer to [microsoft/vscode](https://github.com/microsoft/vscode) for this.

**Comment by valentjn** [comment]
The documentation is available here: https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#keyboard-shortcuts-for-quick-fixes

**Comment by lrnv** [comment]
Hey, 

What do you propose we do concerning the bug in VS Code ? I am not sure if I understand enough of the matter to open an issue in VS Code repo myself, and having shortcuts for adding to dictionary would be very great.
