### ISSUE TITLE
Delay Runs after Quick Fix or Enable Quick Fix while Running

### ISSUE THREAD

**Issue by alexandres** [valentjn/vscode-ltex#390]
**Is your feature request related to a problem? Please describe.**

When using the Quick fix "Add _ to dictionary", LTeX re-runs immediately for the entire document. For long documents, this makes it very slow to correct errors, since Quick fixes are disabled while LTeX is running. I've tried setting LTeX frequency to 'Manual' but it still runs immediately. I don't mind if the "Problems" corresponding to the added word are not cleared immediately after adding it to the dictionary. 

**Describe the solution you'd like**

Either respect the 'Manual' setting, or don't disable Quick fixes while LTeX is running.

**Describe alternatives you've considered**

Right now I'm manually editing the .vscode/ltex.dictionary.en-US.txt file to sidestep this issue.

**Additional context**

None.

**Comment by valentjn** [comment]
Thanks for the feature request. The problem is that LanguageTool (LT) was reinitialized when the dictionary changed, which cleared the sentence cache. This means a full recheck of the document, not an incremental one.

I mitigated this by having LT<sub>E</sub>X filter out unknown word rule matches when the word is in the dictionary, and not reinitializing LT with the new dictionary when it changes. This might result in slightly different diagnostics and correction suggestions (`Use '...'` quick fixes) after adding a word to the dictionary compared to closing and reopening the document as LT might use the dictionary to alter its behavior, but at least we don't have to reinitialize LT anymore.

The same holds for the `Disable rule` quick fix. LT<sub>E</sub>X now takes care of filtering out matches of disabled rules itself, so that we don't have to supply the disabled rules to LT anymore.

Regarding `ltex.checkFrequency`, [the documentation is pretty clear about that](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexcheckfrequency) (emphasis mine&mdash;the dictionary is part of the settings):

> `"manual"`: Documents are not checked automatically, **except when the settings change.** Use commands such as [`LTeX: Check Current Document`](https://valentjn.github.io/vscode-ltex/docs/commands.html#ltex-check-current-document) to manually trigger checks.

**Comment by valentjn** [comment]
Fix released in 12.0.0.
