### ISSUE TITLE
Start java process lazy / if necessary

### ISSUE THREAD

**Issue by hirschsn** [valentjn/vscode-ltex#4]
Every new vscode window starts a java process, even if the window is empty or the project does not contain any latex files.

Optimal behaviour: Java-Process starts not until a latex file is opened.

**Comment by valentjn** [comment]
I think the fact that a new LS is opened for every VS Code window is by design, as it's supposed to work in a multi-user, multi-window (other workspaces can have different extension settings), and multi-editor (other editors can connect to the LS, too) environment. So this would be an upstream issue of the LSP specs or VS Code.

It should, however, not be necessary to have a server if there's no LaTeX file (or none of the supported file types) currently opened. The `activationEvents` in `package.json` control when the whole extension is activated. If I open a new VS Code window with a workspace where only a file of some unrelated type (MATLAB) is opened, the extension is still activated. I see this in `Output -> Log (Extension Host)`:
```
ExtensionService#_doActivateExtension valentjn.vscode-ltex {"startup":false,"activationEvent":"onLanguage:plaintext"}
```
If I remove `onLanguage:plaintext` from the `activationEvents`, the extension is not loaded (you can test it too in `.vscode/extensions/.../package.json`). So this seems like a bug in VS Code to me.

**Comment by valentjn** [comment]
See upstream issue for more info: https://github.com/microsoft/vscode/issues/80268

**Comment by valentjn** [comment]
Bug has been confirmed upstream. Seems plaintext is used as a fallback if the language mode cannot be detected.

**Comment by valentjn** [comment]
Now that I think about it... Most people don't want to check `plaintext` documents anyway, as an untitled plaintext file can just be some copy/pasted code, data, etc. I could imagine there would be lots of errors for these types of files.

`plaintext` doesn't necessarily mean "text in some natural language that can be spellchecked," but rather "file with arbitrary text (= not a binary file) that can't be classified as a specific known file type."

So we'll just remove the `onLanguage:plaintext` activation event. People will still be able to check text files if they switch the language to `markdown`.
