### ISSUE TITLE
Punctuation in German Markdown headings

### ISSUE THREAD

**Issue by TimTechDev** [valentjn/vscode-ltex#419]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**  
The rule `PUNCTUATION_PARAGRAPH_END` is active on Markdown headings, when in `de-DE`. This causes trouble because, in general, headlines used in long form documents are written without final punctuation. Also, this rule conflicts in this case with [markdownlint](https://github.com/DavidAnson/markdownlint) rule [MD026](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading).

**Describe the solution you'd like**  
Since I didn't find this behaviour in `en-GB`, I would suggest to also disable this rule in German.

**Describe alternatives you've considered**  
I tried to hide these cases as false positives, but at a large scale it becomes quite bothersome.

**Additional context**

![Screenshot A](https://user-images.githubusercontent.com/64265106/136086096-9ccdddc0-88bc-4b3c-a3f2-29fa92731b93.png)
![Screenshot B](https://user-images.githubusercontent.com/64265106/136086102-ecf10940-39d0-4833-ad82-259e64f0b8ec.png)

**Comment by valentjn** [comment]
I can't reproduce this with default settings, only when using picky rules (via [`ltex.additionalRules.enablePickyRules`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexadditionalrulesenablepickyrules)). Are you using picky rules? If yes, then this is why these rules are called picky and also why they're disabled by default, as they result in more false positives.

Apart from this, the diagnostic is triggered by the period after the section number `4.1.2`. According to DIN 5008, you shouldn't insert a period after the section number anyway (see [here](https://de.wikipedia.org/w/index.php?title=Gliederung&oldid=215546827#Dezimale_Gliederung) and [here](https://de.wikipedia.org/w/index.php?title=Gliederung&oldid=215546827#H%C3%A4ufig_vorkommende_Gliederungsfehler)), so that diagnostic will vanish. (In general, I'd advise against manual section numbers and let Pandoc or whatever viewer/tool you're using take care of that, but that's a matter of personal taste.)

**Comment by TimTechDev** [comment]
Thanks for answering to my issue :)

> Are you using picky rules?

Now that you ask, yes. I may have enabled it, since the description of the setting mentions stuff I want to avoid, like sentence length. May I suggest adding a part about false positives in this description, since this wasn't obvious to me.

> According to DIN 5008, you shouldn't insert a period after the section number anyway (see here and here), so that diagnostic will vanish.

I didn't know that. And yes the deletion of the period removes the warning.

> In general, I'd advise against manual section numbers and let Pandoc or whatever viewer/tool you're using take care of that, but that's a matter of personal taste.

That wasn't possible in this case. Usually I also let my computer do it.

**Comment by valentjn** [comment]
Added a hint about more false positives to the docs. Thanks for the suggestion.

**Comment by valentjn** [comment]
Docs fixed in 12.0.0.
