### ISSUE TITLE
Language names are shown as spelling mistakes.

### ISSUE THREAD

**Issue by chirag127** [valentjn/vscode-ltex#456]
Note: It is highly recommended to follow the instructions at https://valentjn.github.io/ltex/vscode-ltex/contributing.html#how-to-report-bugs and use the `LTeX: Report bug in LTeX` command from within Visual Studio Code. Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Describe the bug**
Language names are shown as spelling mistakes/

**Steps to reproduce**

1. Go to vs code.
2. Click on new file.
3. Make a new markdown file.
4. paste following text.
  1. Afrikaans
  2. Albanian
  3. Amharic
  4. Arabic
  5. Armenian
  6. Azerbaijani
  7. Basque
  8. Belarusian
  9. Bengali
  10. Bosnian
  11. Bulgarian
  12. Catalan
  13. Cebuano
  14. Chichewa
  15. Chinese (Simplified)
  16. Chinese (Traditional)
  17. Corsican
  18. Croatian
  19. Czech
  20. Danish
  21. Dutch
  22. English
  23. Esperanto
  24. Estonian
  25. Filipino
  26. Finnish
  27. French
  28. Frisian
  29. Galician
  30. Georgian
  31. German
  32. Greek
  33. Gujarati
  34. Haitian Creole
  35. Hausa
  36. Hawaiian
  37. Hebrew
  38. Hindi
  39. Hmong
  40. Hungarian
  41. Icelandic
  42. Igbo
  43. Indonesian
  44. Irish
  45. Italian
  46. Japanese
  47. Javanese
  48. Kannada
  49. Kazakh
  50. Khmer
  51. Korean
  52. Kurdish (Kurmanji)
  53. Kyrgyz
  54. Lao
  55. Latin
  56. Latvian
  57. Lithuanian
  58. Luxembourgish
  59. Macedonian
  60. Malagasy
  61. Malay
  62. Malayalam
  63. Maltese
  64. Maori
  65. Marathi
  66. Mongolian
  67. Myanmar (Burmese)
  68. Nepali
  69. Norwegian
  70. Odia
  71. Pashto
  72. Persian
  73. Polish
  74. Portuguese
  75. Punjabi
  76. Romanian
  77. Russian
  78. Samoan
  79. Scots Gaelic
  80. Serbian
  81. Sesotho
  82. Shona
  83. Sindhi
  84. Sinhala
  85. Slovak
  86. Slovenian
  87. Somali
  88. Spanish
  89. Sundanese
  90. Swahili
  91. Swedish
  92. Tajik
  93. Tamil
  94. Telugu
  95. Thai
  96. Turkish
  97. Ukrainian
  98. Urdu
  99. Uzbek
  100. Vietnamese
  101. Welsh
  102. Xhosa
  103. Yiddish
  104. Yoruba
  105. Zulu
5. See error.

**Expected behavior**
A clear and concise description of what I expected to happen is that Language names are not shown as spelling mistakes.

**Additional context/information**

I think that legitimate language names should not be shown as possible spelling mistake.

**Comment by valentjn** [comment]
I get seven diagnostics for your document, for `Igbo`, `Kyrgyz`, `Luxembourgish`, `Odia`, `Shona`, `Sinhala`, and `Tajik`. There are no diagnostics for the 98 other items.

I'm not sure what the expected behavior is.
- Do you want no diagnostics at all for any of those items? Then add them to the dictionary by using `Add '...' to the dictionary`.
- Do you expect to have no diagnostics by default (i.e., without having the user add the unknown words to the dictionary)? Then open an issue over at [LanguageTool](https://github.com/languagetool-org/languagetool), which is LT<sub>E</sub>X's backend for checking. But in every spell-checking software, there will always be obscure words that it won't know, so I wouldn't expect to have zero diagnostics. That's why most spell-checkers have user dictionaries.

Either way, it's not an LT<sub>E</sub>X issue.

**Comment by chirag127** [comment]
Well 
In my opinion, the names of Languages should be in dictionary by default.

I was confused if I should write the issue in bug or feature requests.

**Comment by valentjn** [comment]
If you want to add words to the default dictionary, you need to head over to [LanguageTool](https://github.com/languagetool-org/languagetool). LT<sub>E</sub>X is only the frontend and does not have/manage any default dictionaries.

However, as I wrote, there's always going to be words (whether the name of a language or not) that are not covered by built-in dictionaries. It's easier to just add them to your user dictionary.
